const fs = require('fs');
const path = require('path');

// Grab the environment variable from Cloudflare
const backendUrl = process.env.VITE_BACKEND_URL;

if (!backendUrl) {
    console.error('\n\x1b[31m%s\x1b[0m', '❌ ERROR: VITE_BACKEND_URL environment variable is MISSING!');
    console.error('\x1b[33m%s\x1b[0m\n', 'Set VITE_BACKEND_URL in Cloudflare Pages -> Settings -> Environment Variables, then retry.');
    process.exit(1);
}

// Write a config.js file that sets a global variable
// This is injected BEFORE script.js in index.html, so it is always available
const configPath = path.join(__dirname, 'config.js');
const configContent = `// Auto-generated by build.js at deploy time. Do NOT edit manually.\nwindow.BACKEND_URL = '${backendUrl}';\n`;

fs.writeFileSync(configPath, configContent);

console.log('\x1b[32m%s\x1b[0m', `✅ config.js written with BACKEND_URL: ${backendUrl}`);

// Generate _redirects for Cloudflare Pages
// Fallback: serves post.html for /blog/* URLs not matched by a pre-rendered file.
const redirectsPath = path.join(__dirname, '_redirects');
const redirectsContent = `# Auto-generated by build.js at deploy time.
# Pre-rendered blog/<slug>/index.html files are served first (static assets).
# This fallback covers any slug not yet pre-rendered.
/blog/*  /post.html  200
`;

fs.writeFileSync(redirectsPath, redirectsContent);

console.log('\x1b[32m%s\x1b[0m', '✅ _redirects written with /blog/* -> /post.html fallback');

// --- Pre-render blog post pages with OG meta tags for social sharing ---

function escapeAttr(text) {
    if (!text) return '';
    return text.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function httpGetJson(url) {
    return new Promise((resolve, reject) => {
        const lib = url.startsWith('https') ? require('https') : require('http');
        lib.get(url, (res) => {
            if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
                return httpGetJson(res.headers.location).then(resolve, reject);
            }
            let body = '';
            res.on('data', chunk => body += chunk);
            res.on('end', () => {
                if (res.statusCode >= 200 && res.statusCode < 300) {
                    try { resolve(JSON.parse(body)); }
                    catch (e) { reject(new Error('Invalid JSON from API')); }
                } else {
                    reject(new Error(`API returned HTTP ${res.statusCode}`));
                }
            });
        }).on('error', reject);
    });
}

async function prerenderBlogPages() {
    const template = fs.readFileSync(path.join(__dirname, 'post.html'), 'utf-8');

    const data = await httpGetJson(`${backendUrl}/api/posts`);
    if (!data.items || data.items.length === 0) {
        console.log('⚠️  No blog posts found for pre-rendering');
        return;
    }

    let count = 0;
    for (const item of data.items) {
        const fields = item.fields;
        const slug = fields.slug;
        if (!slug) continue;

        const title = escapeAttr(fields.title || fields.tittle || 'Article');
        const description = escapeAttr(fields.excerpt || title);
        const postUrl = `https://samabrains.com/blog/${slug}`;

        // Resolve cover image from Contentful includes
        let imageUrl = '';
        if (fields.coverImage && fields.coverImage.sys && data.includes && data.includes.Asset) {
            const asset = data.includes.Asset.find(a => a.sys.id === fields.coverImage.sys.id);
            if (asset && asset.fields && asset.fields.file && asset.fields.file.url) {
                imageUrl = `https:${asset.fields.file.url}`;
            }
        }

        // Clone template and inject OG meta tags
        let html = template;
        html = html.replace(/<title>.*?<\/title>/, `<title>${title} | SamaBrains Blog</title>`);
        html = html.replace(/<meta name="description" content=".*?">/, `<meta name="description" content="${description}">`);
        html = html.replace(/<meta property="og:title" content=".*?">/, `<meta property="og:title" content="${title}">`);
        html = html.replace(/<meta property="og:description" content=".*?">/, `<meta property="og:description" content="${description}">`);
        html = html.replace(/<meta property="og:image" content=".*?">/, `<meta property="og:image" content="${imageUrl}">`);
        html = html.replace(/<meta property="og:url" content=".*?">/, `<meta property="og:url" content="${postUrl}">`);
        html = html.replace(/<meta name="twitter:title" content=".*?">/, `<meta name="twitter:title" content="${title}">`);
        html = html.replace(/<meta name="twitter:description" content=".*?">/, `<meta name="twitter:description" content="${description}">`);
        html = html.replace(/<meta name="twitter:image" content=".*?">/, `<meta name="twitter:image" content="${imageUrl}">`);

        const dir = path.join(__dirname, 'blog', slug);
        fs.mkdirSync(dir, { recursive: true });
        fs.writeFileSync(path.join(dir, 'index.html'), html);
        count++;
    }

    console.log('\x1b[32m%s\x1b[0m', `✅ Pre-rendered ${count} blog post pages with OG meta tags`);
}

prerenderBlogPages().catch(err => {
    console.error('\x1b[33m%s\x1b[0m', `⚠️  Pre-rendering skipped (posts still work via JS): ${err.message}`);
});

