const fs = require('fs');
const path = require('path');

// Grab the environment variable from Cloudflare
const backendUrl = process.env.VITE_BACKEND_URL;

if (!backendUrl) {
    console.error('\n\x1b[31m%s\x1b[0m', '❌ ERROR: VITE_BACKEND_URL environment variable is MISSING!');
    console.error('\x1b[33m%s\x1b[0m\n', 'Set VITE_BACKEND_URL in Cloudflare Pages -> Settings -> Environment Variables, then retry.');
    process.exit(1);
}

// Write a config.js file that sets a global variable
// This is injected BEFORE script.js in index.html, so it is always available
const configPath = path.join(__dirname, 'config.js');
const configContent = `// Auto-generated by build.js at deploy time. Do NOT edit manually.\nwindow.BACKEND_URL = '${backendUrl}';\n`;

fs.writeFileSync(configPath, configContent);

console.log('\x1b[32m%s\x1b[0m', `✅ config.js written with BACKEND_URL: ${backendUrl}`);

// Generate _redirects for Cloudflare Pages
// Proxies /blog/* to the backend for server-side OG meta tag injection
const redirectsPath = path.join(__dirname, '_redirects');
const redirectsContent = `# Auto-generated by build.js — proxies blog URLs to backend for SSR OG tags
/blog/*  ${backendUrl}/api/blog-page/:splat  200
`;

fs.writeFileSync(redirectsPath, redirectsContent);

console.log('\x1b[32m%s\x1b[0m', `✅ _redirects written with proxy to ${backendUrl}`);

